### ISSUE TITLE
FROM lsiobase/xenial-root-armhf -> dockerhub image tagged with bionic 

### ISSUE THREAD

**Issue by trasba** [linuxserver/docker-baseimage-ubuntu-armhf#9]
Hi there,

is this still up to date?
Dockerfile  -> FROM lsiobase/xenial-root-armhf
but in dockerhub there is an image tagged with bionic.
https://hub.docker.com/r/lsiobase/ubuntu.armhf/tags/
That seems weird.
By the way where do I find the Dockerfile of the root image?
Is it lsiobase/xenial-root-armhf -> linuxserver/rootfs-builder-ubuntu ?

**Comment by sparklyballs** [comment]
there are branches in this repository and while we're in the process of updating downstream images, some will be using xenial and others bionic.

when we have transferred as many images that will accept being run under bionic, bionic will become the master branch.

**Comment by trasba** [comment]
Oh didn't see that.
Thanks for the heads up.
Are there no Dockerfiles for the source images?
lsiobase/bionic-root-armhf / lsiobase/xenial-root-armhf
